# Generated by Django 5.2 on 2025-10-02 11:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 10, 2, 11, 0, 58, 363768, tzinfo=datetime.timezone.utc))),
                ('publication_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField()),
                ('text', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2025, 10, 2, 11, 0, 58, 364216, tzinfo=datetime.timezone.utc))),
                ('approved', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.post')),
            ],
        ),
    ]
