# Generated by Django 5.2 on 2025-10-02 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_alter_comment_creation_date_alter_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 2, 11, 48, 20, 937372, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 2, 11, 48, 20, 936869, tzinfo=datetime.timezone.utc)),
        ),
    ]
