# Generated by Django 5.2 on 2025-10-02 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_alter_comment_creation_date_alter_post_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 2, 12, 7, 6, 763816, tzinfo=datetime.timezone.utc)),
        ),
    ]
