# Generated by Django 5.2 on 2025-12-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_alter_post_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_Published',
            field=models.BooleanField(default=False),
        ),
    ]
